version=1.0.0
update.githubRepo=https://github.com/EduCore-Development/eduxel-server-application-installer
update.versionUrl=
app.name=Eduxel
app.version=1.0.0
app.build=2025-12-30
webapp.releaseUrl=https://github.com/EduCore-Development/eduxel-webdash/releases/latest
